name: sandbox_core
description: A new Flutter package project.
version: 0.0.1 

environment:
  sdk: ">=2.17.5 <3.0.0"  
  flutter: ">=1.17.0"

dependencies:
  # Http requests management
  dio: ^4.0.6
  
  # Logger
  sandbox_logger: ^1.0.4

  # Code lock mechanism
  synchronized: ^3.0.0+2

  # For storage manegment and cache
  get_storage: ^2.0.3

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0